### ISSUE TITLE
Looking for help to maintain django-cookie-consent

### ISSUE THREAD

**Issue by bmihelac** [jazzband/django-cookie-consent#38]
I'm looking for somebody that can help maintain django-cookie-consent.

Any candidate?

**Comment by 9mido** [comment]
@bmihelac How about making this a jazzband project? That way, the entire django community can maintain it. This is by far the best cookie library for django since it completely replaces paid solutions. I think it would be great for the community to have this project.

**Comment by bmihelac** [comment]
Hi and thanks for your answer @9mido . 
jazzband is great and I would be glad to transfer project but I am not sure if it would be interesting for jazzband, given the relatively number of stars django-cookie-consent has.

**Comment by 9mido** [comment]
@bmihelac You're welcome. Glad to see your thoughts on this. Maybe contact some of the jazzband people and see what they think. Even if it may not have enough stars, you could argue that cookie management is an essential part of the web nowadays. The laws could change at any time and this would be a great library to respond to those changing laws. I feel like most developers ignore the laws or are just don't know about them which is why this library does not have a lot of stars. Once part of jazzband, I would imagine the marketing and visibility of this library would become much more popular than it already is. There are also other cookie libraries on PyPi but none of them are as good at managing cookies as this one. This one should be the gold standard out of all of those other django cookie libraries. Without a cookie management solution, django developers everywhere could face very high fines. Just for those reasons, jazzband should adopt this project, regardless of the number of stars that it has. Plus it completely replaces something paid like OneTrust CookiePro and that alone makes it a very desirable django library.

**Comment by sergei-maertens** [comment]
@bmihelac are there any things in particular that need (urgent) attention?

Usually I get some time for contributing back to open-source on company time and we have the process of 3rd-party packages pretty fleshed out.

**Comment by sergei-maertens** [comment]
Small update to the community - I have maintainer rights on the repository now and should have some time to keep an eye on things :) Feel free to ping me if I'm missed something or input is required.

I need to get a bit more into the nitty-gritty implementation details and will probably first focus on open PRs, issues and general project maintenance (think documentation, CI...)

**Comment by some1ataplace** [comment]
Thanks for the update @sergei-maertens. 

I still would love for this library to be transferred to jazzband to ensure its long term survival. In order to do that though, @bmihelac must follow the links above to initiate the transfer when he is able to.

**Comment by sergei-maertens** [comment]
I'm going to close this issue - note however that I'm trying to get it transferred out of jazzband again as they are currently the blocking factor for getting new versions on PyPI.
