### ISSUE TITLE
from django.contrib.auth.views import SuccessURLAllowedHostsMixinImportError: cannot import name 'SuccessURLAllowedHostsMixin' from 'django.contrib.auth.views'

### ISSUE THREAD

**Issue by Dionise** [jazzband/django-cookie-consent#73]

**Comment by tobiaspatzer** [comment]
[The undocumented django.contrib.auth.views.SuccessURLAllowedHostsMixin mixin is replaced by RedirectURLMixin.](https://docs.djangoproject.com/en/4.1/releases/4.1/)

I can't find the import, but I think this needs to be replaced

**Comment by sergei-maertens** [comment]
Fixed via 54f5e5fae0b5d94e34d09385b5e4cd87d5e2c6a6

**Comment by nerdoc** [comment]
Would you mind releasing an updated package, so that Django 4.1 users can use django-cookie-consent again? Thanks in advance!

**Comment by sergei-maertens** [comment]
I definitely do not mind, but unfortunately it's not super straight forward at the moment :grimacing: 

Ideally, I'd like to resolve two more issues in the 0.4.0 release (see the [milestone](https://github.com/jazzband/django-cookie-consent/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Release+0.4.0%22)).

And we currently also have a blocking issue that blocks the entire release flow due to the transfer to Jazzband: https://github.com/jazzband/django-cookie-consent/issues/64#issuecomment-1256945503

I have not been able to get in touch with the roadie of Jazzband and don't have sufficient permissions to be able to approve releases in the jazzband website myself (as I'm not a team lead yet). This is all related to jazzband/help#196 which does not seem to go anywhere.
